### ISSUE TITLE
Error when running on bash in windows

### ISSUE THREAD

**Issue by deepu105** [joewalnes/greendots#7]
Super awesome (terrible) project :)
I'm getting below issue
```
deepu@DEE-ASUS:~/greendots$ ./greendots.py "JHI" ../my-greendot-repo/make.sh
Traceback (most recent call last):
  File "./greendots.py", line 72, in <module>
    main()
  File "./greendots.py", line 38, in main
    canvas.apply(label, x=canvas.width - label.width)  # right align
  File "/home/deepu/greendots/bitmap.py", line 14, in apply
    old = self.data[y + py][x + px]
IndexError: list index out of range
deepu@DEE-ASUS:~/greendots$
``

**Comment by joewalnes** [comment]
Hmm. Which python do you have? I've only tested with 2.7

**Comment by deepu105** [comment]
Ok seems like it works only when i pass all 6 chars atleast as empty space. I'm having 2.7 as well
